In [10]:
import numpy as np
def arrayfill(a,r,c,prev_fill,to_fill):
    if r>len(a)-1 or c>len(a)-1 or r<0 or c<0:
        return
    if a[r][c] != prev_fill:
        return
        
    else:
        a[r][c] = to_fill
        arrayfill(a,r+1,c,prev_fill,to_fill)
        arrayfill(a,r-1,c,prev_fill,to_fill)
        arrayfill(a,r,c+1,prev_fill,to_fill)
        arrayfill(a,r,c-1,prev_fill,to_fill)
arr=[[1,2,2,1],[2,1,2,2],[1,2,2,2],[2,1,1,2]]
a=np.array(arr)
r=1
c=2
prev_fill=2
to_fill=3
print(a)
print("after fill")
arrayfill(a,r,c,prev_fill,to_fill)
print(a)

[[1 2 2 1]
 [2 1 2 2]
 [1 2 2 2]
 [2 1 1 2]]
after fill
[[1 3 3 1]
 [2 1 3 3]
 [1 3 3 3]
 [2 1 1 3]]
